apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-master-pv
    namespace: wordpress
spec:
    capacity:
       storage: 3G
    accessModes:
       - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      server: 192.168.47.202
      path: /data01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-data-pvc
    namespace: wordpress
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 3G
