apiVersion: v1
kind: PersistentVolume
metadata:
    name: wordpress-pv
    namespace: wordpress
spec:
    capacity:
       storage: 4G
    accessModes:
       - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      server: 192.168.47.202
      path: /data03
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wordpress-pvc
    namespace: wordpress
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 4G
